---
name: default
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: bootlegger/titan-compact
    dockerfile: install/Dockerfile
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - TARGETPLATFORM=linux/arm/v7
    context: install/
