trigger:
  tags:
    include:
    - '*'

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  name: 'DownloadPrerequesits'
  inputs:
    filePath: 'Bootlegger.Application.Lib\\downloads\\getinstallers.ps1'
    workingDirectory: 'Bootlegger.Application.Lib\\downloads'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:RunWixToolsOutOfProc=true'


- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'OurStory GitHub'
    repositoryName: 'our-story-media/ourstory-titan'
    action: 'create'
    title: 'Our Story Titan Installer'
    addChangeLog: false
    assets: 'install/*.exe'