trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  name: 'DownloadPrerequesits'
  inputs:
    filePath: 'Bootlegger.Application.Lib\\downloads\\getinstallers.ps1'
    workingDirectory: 'Bootlegger.Application.Lib\\downloads'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:RunWixToolsOutOfProc=true'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: 'install/OurStoryToolbox.exe'
#     ArtifactName: 'Toolbox'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: 'install/OurStoryHyperV.exe'
#     ArtifactName: 'HyperV'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'OurStory GitHub'
    repositoryName: 'our-story-media/ourstory-titan'
    action: 'create'
    title: 'Installer'
    addChangeLog: false
    assets: 'install/*.exe'