version: "2"

volumes:
  mongo-data:
    external: false
  redis-data:
    external: false

services:
  nginx-local:
    restart: on-failure
    image: bootlegger/nginx-local
    ports:
      - "80:80"
    volumes:
      - "./upload:/usr/src/app/upload"
    volumes_from:
      - web

  redis:
    restart: on-failure
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  mongo:
    restart: on-failure
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  beanstalk:
    restart: on-failure 
    image: kusmierz/beanstalkd

  worker:
    restart: on-failure
    image: bootlegger/ourstory-worker:latest
    depends_on:
      - mongo
      - beanstalk
    volumes_from:
      - web
    volumes:
      - "./upload:/usr/src/app/upload"

  web:
    restart: on-failure
    image: bootlegger/ourstory-server:latest
    depends_on: 
      - redis
      - mongo
      - beanstalk
    volumes:
      - "./upload:/usr/src/app/upload"